# Generated by Django 6.0.5 on 2026-05-18 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('alternative_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('ghana_card_id', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(max_length=100)),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_source', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('AH', 'Ahafo Region'), ('AR', 'Ashanti Region'), ('BO', 'Bono East Region'), ('BR', 'Bono Region'), ('CR', 'Central Region'), ('ER', 'Eastern Region'), ('GAR', 'Greater Accra Region'), ('NER', 'North East Region'), ('NR', 'Northern Region'), ('OR', 'Oti Region'), ('SAR', 'Savannah Region'), ('UER', 'Upper East Region'), ('UWR', 'Upper West Region'), ('VR', 'Volta Region'), ('WR', 'Western Region'), ('WNR', 'Western North Region')], max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('gps_address', models.CharField(blank=True, max_length=50, null=True)),
                ('guarantor_name', models.CharField(max_length=200)),
                ('guarantor_phone', models.CharField(max_length=15)),
                ('guarantor_ghana_card', models.CharField(blank=True, max_length=20, null=True)),
                ('guarantor_relationship', models.CharField(max_length=50)),
                ('customer_photo', models.ImageField(blank=True, null=True, upload_to='customers/')),
                ('guarantor_photo', models.ImageField(blank=True, null=True, upload_to='guarantors/')),
                ('proof_of_income', models.FileField(blank=True, null=True, upload_to='income_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_customers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IphoneDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('iPhone 14', 'iPhone 14 - GHS 8,500'), ('iPhone 14 Pro', 'iPhone 14 Pro - GHS 11,000'), ('iPhone 14 Pro Max', 'iPhone 14 Pro Max - GHS 12,500'), ('iPhone 15', 'iPhone 15 - GHS 10,500'), ('iPhone 15 Pro', 'iPhone 15 Pro - GHS 14,000'), ('iPhone 15 Pro Max', 'iPhone 15 Pro Max - GHS 16,000'), ('iPhone 16', 'iPhone 16 - GHS 18,000')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('simplemdm_udid', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='accounts.customer')),
                ('last_locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily (180 payments)'), ('weekly', 'Weekly (26 payments)'), ('monthly', 'Monthly (6 payments)')], max_length=10)),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_installments', models.IntegerField()),
                ('payments_made', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.iphonedevice')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('lock', 'Device Locked'), ('unlock', 'Device Unlocked'), ('payment', 'Payment Made'), ('customer_registration', 'Customer Registered'), ('device_assigned', 'Device Assigned'), ('plan_created', 'Installment Plan Created')], max_length=50)),
                ('details', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.iphonedevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.customer')),
                ('installment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.installmentplan')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
